"""
Django settings for controle_industrial project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$z40rb_%1&#=h0f$3-fa==3y$!dwfq%5n!w*2h-_$n7j$hbf#v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #'ibgcontrole',
    #'cadastros',
    #'producao',
    'django_bootstrap5',
    'crispy_forms',
    'crispy_bootstrap5',
    'dal',
    'dal_select2',
    'django.contrib.humanize',
    'sisven_users',
    'sisven_consulta_precos',
    'sisven_conf_comissoes',
    'sisven_core',
    'core', 

]

CRISPY_TEMPLATE_PACK = 'bootstrap5'
CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'controle_industrial.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'base_templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.menu_processor', 
            ],
        },
    },
]

WSGI_APPLICATION = 'controle_industrial.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    #'default': {
    #    'ENGINE': 'django.db.backends.sqlite3',
    #    'NAME': BASE_DIR / 'db.sqlite3',
    #},

    'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'controle_ibg',
            'USER': 'root',
            'PASSWORD': 'Ibg_6000@',
            'HOST': 'localhost',
            'PORT': '3306',
    },

    'acedata': {
        'ENGINE': 'mssql',
        'NAME': 'ibgdb',
        'USER': 'marcos',
        'PASSWORD': 'ibg_6000',
        'HOST': '192.168.1.181',  # Ex: '192.168.1.100' ou o nome do servidor
        'PORT': '1433',                      # Porta padrão do SQL Server

        'OPTIONS': {
            # Use o nome exato do driver moderno instalado. Ex:
            'driver': 'ODBC Driver 18 for SQL Server', 
            # Adicione esta linha para confiar no certificado do servidor
            'extra_params': 'TrustServerCertificate=yes',
            # Diz ao Django para não fazer conversões de timezone para esta conexão
            'use_tz': False,
        },
        
    },
    
    'sisven': {
        'ENGINE': 'django.db.backends.mysql', # Ou o engine do seu banco: postgresql, oracle, etc.
        'NAME': 'sisventestebkp',
        'USER': 'root',
        'PASSWORD': 'Ibg_6000@',
        'HOST': 'localhost', # ex: '192.168.1.100'
        'PORT': '3306', # Porta padrão do MySQL
    },
}

DATABASE_ROUTERS = ['sisven_core.routers.LegadoRouter']

AUTHENTICATION_BACKENDS = [
    'sisven_core.authentication.SisvenAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'base_static']
STATIC_ROOT = BASE_DIR / 'static'
MEDIA_URL = 'media/'  # Arquivos enviados pelo usuário
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CRISPY_TEMPLATE_PACK = 'bootstrap5'
DATA_UPLOAD_MAX_NUMBER_FIELDS = None


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} - {levelname} - {name} - {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            # Caminho mais robusto para o arquivo de log
            'filename': os.path.join(BASE_DIR, 'importacao_ops.log'),
            'mode': 'w',
            'formatter': 'verbose',
        },
    },
    # A mudança principal está aqui: configuramos o logger 'root'
    'root': {
        'handlers': ['file'], # Envia tudo para o nosso manipulador de arquivo
        'level': 'DEBUG',      # Captura todas as mensagens a partir do nível DEBUG
    },
}

LOGIN_URL = 'login'  # O nome da sua URL de login
LOGOUT_REDIRECT_URL = 'login' # Para onde redirecionar após o logout (ex: página inicial)
LOGIN_REDIRECT_URL = 'core:index'
