# Generated by Django 4.2.21 on 2025-08-08 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0006_alter_setor_table'),
        ('ibgcontrole', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cid01',
            fields=[
                ('cidcod', models.CharField(db_column='CidCod', max_length=50, primary_key=True, serialize=False)),
                ('cidnom', models.CharField(db_column='CidNom', max_length=255)),
                ('estcod', models.CharField(db_column='EstCod', max_length=2)),
            ],
            options={
                'db_table': 'cid01',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Emb01',
            fields=[
                ('embcod', models.CharField(db_column='EmbCod', max_length=50, primary_key=True, serialize=False)),
                ('embnom', models.CharField(db_column='EmbNom', max_length=255)),
            ],
            options={
                'db_table': 'emb01',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ftc01',
            fields=[
                ('ftcacod', models.CharField(db_column='FtcACod', max_length=50, primary_key=True, serialize=False)),
                ('ftcanom', models.CharField(db_column='FtcANom', max_length=255)),
                ('ftcaqtdbas', models.DecimalField(db_column='FtcAQtdBas', decimal_places=4, max_digits=19)),
            ],
            options={
                'db_table': 'ftc01',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ftc02',
            fields=[
                ('ftcacod', models.CharField(db_column='FtcACod', max_length=50, primary_key=True, serialize=False)),
                ('ftcbitm', models.IntegerField(db_column='FtcBItm', help_text='Sequência do item na fórmula')),
                ('ftcprocod', models.CharField(db_column='FtcBProCod', max_length=50)),
                ('ftcqtd', models.DecimalField(db_column='FtcBQtd', decimal_places=4, max_digits=19)),
            ],
            options={
                'db_table': 'ftc02',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ftd02',
            fields=[
                ('gddcod', models.CharField(db_column='GddCod', max_length=50, primary_key=True, serialize=False)),
                ('ftcacod', models.CharField(db_column='FtcACod', max_length=50)),
                ('ftditm', models.IntegerField(db_column='FtdItm', help_text='Número do Item / Camada')),
                ('mtgcod', models.CharField(blank=True, db_column='MtgCod', max_length=50, null=True)),
            ],
            options={
                'db_table': 'ftd02',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ftm01',
            fields=[
                ('ftmacod', models.CharField(db_column='ftmacod', max_length=50, primary_key=True, serialize=False)),
                ('ftmanom', models.CharField(db_column='ftmanom', max_length=255)),
                ('ftmacam', models.IntegerField(blank=True, db_column='FtmACam', help_text='Número de Camadas', null=True)),
                ('ftmamtgcod', models.CharField(blank=True, db_column='FtmAMtgCod', help_text='Código do Grupo de Material', max_length=50, null=True)),
                ('ftmateqcod', models.CharField(blank=True, db_column='FtmATeqCod', help_text='Código do Equipamento', max_length=50, null=True)),
                ('ftmateqemp', models.CharField(blank=True, db_column='FtmATeqEmp', help_text='Código da Empresa do Equipamento', max_length=10, null=True)),
            ],
            options={
                'db_table': 'ftm01',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ftm02',
            fields=[
                ('ftmacod', models.CharField(db_column='ftmacod', max_length=50, primary_key=True, serialize=False)),
                ('ftmdtam', models.CharField(db_column='ftmdtam', max_length=50)),
                ('ftmdespbru', models.DecimalField(db_column='ftmdespbru', decimal_places=4, max_digits=19)),
                ('ftmdespaca', models.DecimalField(db_column='ftmdespaca', decimal_places=4, max_digits=19)),
                ('ftmdren', models.DecimalField(db_column='FtmDRen', decimal_places=4, max_digits=19)),
                ('ftmdapr', models.DecimalField(db_column='FtmDApr', decimal_places=4, max_digits=19)),
            ],
            options={
                'db_table': 'ftm02',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ftm04',
            fields=[
                ('ftmacod', models.CharField(db_column='FtmAcod', max_length=50, primary_key=True, serialize=False)),
                ('ftmeart', models.CharField(db_column='FtmEArt', max_length=255)),
                ('ftmeobs', models.TextField(blank=True, db_column='FtmEObs', null=True)),
            ],
            options={
                'db_table': 'ftm04',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ftm05',
            fields=[
                ('ftmacod', models.CharField(db_column='FtmACod', max_length=50, primary_key=True, serialize=False)),
                ('ftmbitm', models.IntegerField(db_column='FtmBItm', help_text='Número do Item / Camada')),
                ('ftmbpor', models.DecimalField(db_column='FtmBPor', decimal_places=4, max_digits=19)),
                ('ftmbfix', models.CharField(db_column='FtmBFix', max_length=1)),
            ],
            options={
                'db_table': 'ftm05',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ftm06',
            fields=[
                ('ftmacod', models.CharField(db_column='FtmAcod', max_length=50, primary_key=True, serialize=False)),
                ('ftmhobs', models.TextField(blank=True, db_column='FtmHObs', null=True)),
            ],
            options={
                'db_table': 'ftm06',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Opr01',
            fields=[
                ('opracod', models.CharField(db_column='opracod', max_length=50, primary_key=True, serialize=False)),
                ('opraempcod', models.CharField(db_column='opraempcod', max_length=10)),
                ('opraprocod', models.CharField(db_column='opraprocod', max_length=50)),
                ('opranom', models.CharField(db_column='opranom', max_length=255)),
                ('opraagr', models.CharField(blank=True, db_column='OprAAgr', help_text='Código de Agrupamento', max_length=50, null=True)),
                ('opradatemi', models.DateTimeField(blank=True, db_column='OprADatEmi', help_text='Data de Emissão da OP no ERP', null=True)),
                ('oprapesjt', models.DecimalField(blank=True, db_column='OPRAPESCJT', decimal_places=4, help_text='Peso da Placa', max_digits=19, null=True)),
                ('opraqtdcjt', models.DecimalField(blank=True, db_column='OPRAQTDCJT', decimal_places=4, help_text='Qtde Placas', max_digits=19, null=True)),
                ('oprapesprv', models.DecimalField(blank=True, db_column='OPRAPESPRV', decimal_places=4, help_text='Peso Previsto', max_digits=19, null=True)),
                ('opraqtdped', models.DecimalField(db_column='opraqtdped', decimal_places=4, max_digits=19)),
                ('opraqtdprv', models.DecimalField(db_column='opraqtdprv', decimal_places=4, max_digits=19)),
                ('opragddcod1', models.CharField(db_column='opragddcod1', max_length=50)),
                ('opragddcod2', models.CharField(db_column='opragddcod2', max_length=50)),
                ('opragddcod3', models.CharField(db_column='opragddcod3', max_length=50)),
                ('oprauniest', models.CharField(db_column='oprauniest', max_length=10)),
                ('opraftmcod', models.CharField(db_column='opraftmcod', max_length=50)),
            ],
            options={
                'db_table': 'opr01',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pdv01',
            fields=[
                ('pdvempcod', models.CharField(db_column='PdvEmpCod', max_length=10)),
                ('pdvcod', models.CharField(db_column='PdvCod', max_length=50, primary_key=True, serialize=False)),
                ('pdvrazsoc', models.CharField(db_column='PdvRazSoc', help_text='Nome do cliente (denormalizado no pedido)', max_length=255)),
                ('pdvemi', models.DateField(blank=True, db_column='PdvEmi', null=True)),
            ],
            options={
                'db_table': 'pdv01',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pdv02',
            fields=[
                ('pdvempcod', models.CharField(db_column='pdvempcod', max_length=10)),
                ('pdvcod', models.CharField(db_column='pdvcod', max_length=50)),
                ('pdvoprcod', models.CharField(db_column='pdvoprcod', max_length=50, primary_key=True, serialize=False)),
                ('pdvprocod', models.CharField(db_column='pdvprocod', max_length=50)),
                ('pdvnompro', models.CharField(db_column='pdvnompro', max_length=255)),
                ('pdvunicod', models.CharField(db_column='pdvunicod', max_length=10)),
                ('pdvitmpro', models.CharField(db_column='pdvitmpro', max_length=10)),
                ('pdvgddcod1', models.CharField(db_column='pdvgddcod1', max_length=50)),
                ('pdvgddcod2', models.CharField(db_column='pdvgddcod2', max_length=50)),
                ('pdvgddcod3', models.CharField(db_column='pdvgddcod3', max_length=50)),
                ('pdvterpro', models.CharField(db_column='pdvterpro', max_length=50)),
                ('pdvoprobs', models.CharField(blank=True, db_column='pdvBoprobs', max_length=255, null=True)),
                ('pdvqtdpro', models.DecimalField(db_column='pdvqtdpro', decimal_places=4, max_digits=19)),
                ('pdvboriproqtd', models.DecimalField(db_column='PdvBOriProQtd', decimal_places=4, help_text='Quantidade Original do Pedido', max_digits=19)),
                ('pdvpedcli', models.CharField(blank=True, db_column='PdvPedCli', help_text='Número do pedido do cliente (Ex: 006/25)', max_length=50, null=True)),
                ('pdvtotitm', models.DecimalField(db_column='pdvtotitm', decimal_places=4, max_digits=19)),
                ('pdvprvent', models.DateField(blank=True, db_column='pdvprvent', help_text='Data Previsão de Entrega', null=True)),
                ('pdvprcven', models.DecimalField(blank=True, db_column='PdvPrcVen', decimal_places=4, max_digits=19, null=True)),
                ('pdvemipro', models.DateField(blank=True, db_column='pdvemipro', help_text='Data de Emissão do Pedido', null=True)),
                ('observacao_item', models.TextField(blank=True, db_column='PdvBOprObs', help_text='Observação do item no pedido de venda', null=True)),
            ],
            options={
                'db_table': 'pdv02',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pdv06',
            fields=[
                ('pdvempcod', models.CharField(db_column='pdvempcod', max_length=10)),
                ('pdvcod', models.CharField(db_column='pdvcod', max_length=50, primary_key=True, serialize=False)),
                ('pdvobsdet', models.TextField(blank=True, db_column='PdvObsDet', null=True)),
            ],
            options={
                'db_table': 'pdv06',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pro01',
            fields=[
                ('procod', models.CharField(db_column='procod', max_length=50, primary_key=True, serialize=False)),
                ('pronom', models.CharField(db_column='proNom', max_length=255)),
                ('probarttam', models.CharField(db_column='probarttam', max_length=50)),
                ('probartcod', models.DecimalField(blank=True, db_column='ProBArtCod', decimal_places=0, help_text='Código de Barras do Artigo (numérico)', max_digits=19, null=True)),
                ('proartcodbas', models.DecimalField(blank=True, db_column='ProBArtCodBas', decimal_places=4, help_text='Código do Artigo Base', max_digits=19, null=True)),
                ('prorprcod', models.CharField(db_column='prorprcod', max_length=255)),
                ('propesliq', models.DecimalField(blank=True, db_column='ProPesLiq', decimal_places=6, help_text='Peso Líquido do produto (geralmente por unidade ou grosa)', max_digits=19, null=True)),
            ],
            options={
                'db_table': 'pro01',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rep01',
            fields=[
                ('repdoc', models.CharField(db_column='RepDoc', max_length=50, primary_key=True, serialize=False)),
                ('repnom', models.CharField(db_column='RepNom', max_length=255)),
            ],
            options={
                'db_table': 'rep01',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teq01',
            fields=[
                ('teqcod', models.CharField(db_column='TeqCod', max_length=50, primary_key=True, serialize=False)),
                ('teqnom', models.CharField(db_column='TeqNom', max_length=255)),
                ('mstcod', models.CharField(db_column='MstCod', max_length=10)),
            ],
            options={
                'db_table': 'teq01',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ter01',
            fields=[
                ('terdoc', models.CharField(db_column='TerDoc', max_length=50, primary_key=True, serialize=False)),
                ('ternom', models.CharField(db_column='TerNom', max_length=255)),
            ],
            options={
                'db_table': 'ter01',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgrupamentoLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Agrupamento para Lançamento',
                'verbose_name_plural': 'Agrupamentos para Lançamento',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ControlePolimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ControleProducaoTornoLaser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('OP_1', '1ª Operação'), ('OP_2', '2ª Operação'), ('RETRABALHO', 'Retrabalho'), ('AMOSTRA', 'Amostra'), ('ACABADO', 'Acabado')], max_length=20)),
                ('botoes_por_minuto', models.IntegerField(blank=True, null=True)),
                ('producao_peso', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('quebra_peso', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('check_espessura_cabecote1', models.CharField(blank=True, max_length=50)),
                ('check_espessura_cabecote2', models.CharField(blank=True, max_length=50)),
                ('check_broca', models.CharField(blank=True, max_length=50)),
                ('check_abertura', models.CharField(blank=True, max_length=50)),
                ('check_carregador', models.BooleanField(default=False)),
                ('check_botao', models.BooleanField(default=False)),
                ('check_troca', models.BooleanField(default=False)),
                ('producao_grosas', models.DecimalField(blank=True, decimal_places=2, help_text='Produção em Grôsas, calculada a partir do peso.', max_digits=10, null=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.maquina')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormulaQuimica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_formula', models.CharField(db_index=True, help_text='Código da Fórmula (FTC01.FtcACod)', max_length=50, unique=True)),
                ('nome_formula', models.CharField(help_text='Nome descritivo da fórmula (FTC01.FtcANom)', max_length=255)),
            ],
            options={
                'verbose_name': 'Fórmula Química',
                'verbose_name_plural': 'Fórmulas Químicas',
            },
        ),
        migrations.CreateModel(
            name='ItemDemandaProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido_cliente', models.CharField(blank=True, help_text='Número do pedido do cliente (Ex: 006/25)', max_length=50, null=True)),
                ('cor_final', models.CharField(help_text='Cor final do tingimento (PDV02.pdvgddcod1)', max_length=100)),
                ('quantidade', models.DecimalField(decimal_places=2, help_text='Quantidade desta demanda específica (PDV02.pdvboriproqtd)', max_digits=10)),
                ('preco_venda', models.DecimalField(blank=True, decimal_places=4, help_text='Preço de Venda do item no Pedido (PDV02.PdvPrcVen)', max_digits=19, null=True)),
                ('unidade', models.CharField(blank=True, max_length=10, null=True)),
                ('embalagem', models.CharField(blank=True, max_length=50, null=True)),
                ('observacao_item_pedido', models.TextField(blank=True, null=True, verbose_name='Observação (Item do Pedido)')),
                ('data_entrega', models.DateField(blank=True, help_text='Data de Entrega Prevista (PDV02.pdvprvent)', null=True)),
                ('quantidade_producao', models.DecimalField(decimal_places=2, default=0, help_text='Quantidade de Produção para cálculo financeiro (PDV02.pdvqtdpro)', max_digits=10)),
                ('status_item', models.CharField(choices=[('AGUARDANDO_PRODUCAO', 'Aguardando Produção'), ('AGUARDANDO_TINGIMENTO', 'Aguardando Tingimento'), ('AGUARDANDO_CONTROLE_QUALIDADE', 'Aguardando Controle de Qualidade'), ('EM_TINGIMENTO', 'Em Tingimento'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO_PRODUCAO', max_length=50, verbose_name='Status da Demanda')),
                ('item_pedido_erp', models.CharField(blank=True, help_text='Número do item original do pedido no ERP (PDV02.pdvitmpro)', max_length=10, null=True)),
                ('observacao_pcp', models.TextField(blank=True, null=True, verbose_name='Observação do PCP')),
                ('conferido_em', models.DateTimeField(blank=True, null=True, verbose_name='Conferido em')),
                ('conferido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Conferido por')),
                ('item_programacao', models.ForeignKey(blank=True, help_text='Vínculo com o item da planilha de programação do PCP. Múltiplas demandas podem se vincular a um item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandas_vinculadas', to='ibgcontrole.itemprogramacao')),
            ],
            options={
                'verbose_name': 'Item de Demanda de Produção',
                'verbose_name_plural': 'Itens de Demanda de Produção',
                'ordering': ['ordem_producao', 'pedido'],
            },
        ),
        migrations.CreateModel(
            name='ItemEstoqueKanban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(help_text='Ex: Sumatra, PEC, Cristal', max_length=100)),
                ('cor', models.CharField(help_text='Cor base da matéria-prima, ex: 200, 100, 500', max_length=100)),
                ('tamanho', models.CharField(default='18', help_text="Tamanho padrão para Kanban, geralmente '18'", max_length=50)),
                ('peso_bruto_grosa_medio', models.DecimalField(blank=True, decimal_places=6, help_text='Média ou último valor registrado do peso bruto por grôsa (em gramas). Usado como referência.', max_digits=19, null=True)),
            ],
            options={
                'verbose_name': 'Item de Estoque Kanban',
                'verbose_name_plural': 'Itens de Estoque Kanban',
                'ordering': ['material', 'cor'],
                'unique_together': {('material', 'cor', 'tamanho')},
            },
        ),
        migrations.CreateModel(
            name='LancamentoCilindro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_placas_total', models.DecimalField(decimal_places=4, help_text='Soma total de placas produzidas NESTE lançamento.', max_digits=10)),
                ('quantidade_grosas_total', models.DecimalField(decimal_places=4, default=0, help_text='Soma total de grosas produzidas NESTE lançamento. Calculado automaticamente.', max_digits=10)),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField(null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('agrupamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='producao.agrupamentolancamento')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.maquina', verbose_name='Cilindro')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.operador')),
            ],
            options={
                'verbose_name': 'Lançamento no Cilindro',
                'verbose_name_plural': 'Lançamentos no Cilindro',
                'ordering': ['-data_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='MotivoParada',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MotivoReprogramacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('setor_responsavel', models.CharField(choices=[('QUIMICA', 'Química'), ('PASTILHA', 'Controle de Pastilha'), ('TORNO', 'Torno'), ('LASER', 'Laser'), ('LASER_2', 'Laser 2'), ('POLIMENTO', 'Polimento'), ('TINGIMENTO', 'Tingimento'), ('ESCOLHA_FINAL', 'Escolha Final'), ('CONTAGEM', 'Contagem'), ('ESTEIRA', 'Esteira'), ('KANBAN', 'Kanban'), ('FINALIZADO', 'Finalizado'), ('REPROGRAMADO', 'Reprogramado')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrdemProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_op', models.CharField(help_text='Código da OP (opracod)', max_length=50, unique=True)),
                ('numero_agrupamento', models.CharField(blank=True, help_text='Código de Agrupamento da OP (OprAAgr)', max_length=50, null=True)),
                ('artigo', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('tamanho', models.CharField(max_length=50)),
                ('cor', models.CharField(help_text='Cor base da matéria-prima (OPR01.opragddcod1)', max_length=100)),
                ('furacao', models.CharField(max_length=100)),
                ('acabamento', models.CharField(max_length=100)),
                ('espessura_bruta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('aproveitamento', models.DecimalField(blank=True, decimal_places=2, help_text='Percentual de Aproveitamento (FtmDApr)', max_digits=10, null=True)),
                ('rendimento', models.DecimalField(blank=True, decimal_places=4, help_text='Rendimento em grosas por placa (FtmDRen)', max_digits=19, null=True)),
                ('espessura_acabada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantidade_programada_total', models.DecimalField(decimal_places=2, default=0, help_text='Soma das quantidades de todas as demandas do lote.', max_digits=10)),
                ('unidade', models.CharField(max_length=10)),
                ('data_emissao', models.DateField()),
                ('peso_placa', models.DecimalField(blank=True, decimal_places=4, help_text='Peso da Placa para base da receita (OPRAPESCJT)', max_digits=19, null=True)),
                ('quantidade_placas', models.DecimalField(blank=True, decimal_places=4, help_text='Quantidade de Camadas', max_digits=19, null=True)),
                ('peso_previsto', models.DecimalField(blank=True, decimal_places=4, help_text='Peso Previsto TOTAL da OP (OPRAPESPRV)', max_digits=19, null=True)),
                ('peso_liquido_grosa', models.DecimalField(blank=True, decimal_places=6, help_text='Peso líquido de 1 grosa do produto (do ERP: PRO01.ProPesLiq)', max_digits=19, null=True)),
                ('peso_bruto_grosa', models.DecimalField(blank=True, decimal_places=6, help_text='Campo preparado para receber peso do apontamento da Pastilhas para fazermos termos um padrão do peso bruto da pastilha', max_digits=19, null=True)),
                ('tarja', models.CharField(blank=True, choices=[('AZUL', 'Azul'), ('AMARELO', 'Amarelo'), ('VERMELHO', 'Vermelho'), ('PRETO', 'Preto'), ('VERDE', 'Verde'), ('ROSA', 'Rosa')], help_text='Tarja de prioridade da programação', max_length=20, null=True)),
                ('nome_equipamento', models.CharField(blank=True, help_text='Nome do equipamento (TEQ01.TeqNom)', max_length=255, null=True)),
                ('observacao_ficha_tecnica', models.TextField(blank=True, null=True)),
                ('observacao_material', models.TextField(blank=True, null=True)),
                ('observacao_pedido_venda', models.TextField(blank=True, null=True)),
                ('observacao_op', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE_CONFERENCIA', 'Pendente de Conferência PCP'), ('PENDENTE', 'Pendente'), ('EM_PRODUCAO', 'Em Produção'), ('AGUARDANDO_CORTE', 'Aguardando Corte'), ('PARCIALMENTE_FINALIZADO', 'Parcialmente Finalizado'), ('PAUSADO', 'Pausado'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado'), ('REPROGRAMADO', 'Reprogramado'), ('AGUARDANDO_PASTILHA', 'Aguardando Pastilha')], default='PENDENTE_CONFERENCIA', max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('sequencia_pcp', models.IntegerField(blank=True, db_index=True, help_text='Ordem da sequência de produção importada da planilha do PCP (mantém a primeira ocorrência)', null=True)),
                ('artigo_base', models.CharField(blank=True, db_index=True, help_text='Código do artigo base (ProBArtCodBas) para conciliação', max_length=100, null=True)),
                ('data_qmc', models.DateField(blank=True, db_index=True, help_text='Data de produção da Química importada da planilha do PCP (mantém a primeira ocorrência)', null=True)),
                ('is_kanban', models.BooleanField(db_index=True, default=False, help_text='Indica se a OP segue o fluxo contínuo Kanban')),
                ('requer_tingimento', models.BooleanField(default=False, help_text='Indica se o produto (Kanban ou não) passará pelo processo de tingimento')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(db_index=True, max_length=50, unique=True)),
                ('cliente_nome', models.CharField(max_length=255)),
                ('cliente_codigo', models.CharField(db_index=True, max_length=50)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('representante', models.CharField(blank=True, max_length=100, null=True)),
                ('representante_codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('observacao_detalhada', models.TextField(blank=True, null=True, verbose_name='Observação Detalhada do Pedido')),
            ],
            options={
                'verbose_name': 'Pedido de Venda',
                'verbose_name_plural': 'Pedidos de Venda',
                'ordering': ['-data_emissao', '-numero_pedido'],
            },
        ),
        migrations.CreateModel(
            name='RegraKanban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artigo', models.CharField(help_text='Código do Artigo que pode ser Kanban', max_length=100, unique=True)),
                ('material_nome', models.CharField(help_text='Nome do material (ex: Sumatra, PEC)', max_length=100, null=True)),
                ('material_codigo_erp', models.CharField(help_text='Código do material no ERP (ex: 9, 28, 8)', max_length=20, null=True)),
                ('cor_base_neutra', models.CharField(help_text="A cor base 'neutra' para este material (ex: 200, 100, 500)", max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Regra de Kanban',
                'verbose_name_plural': 'Regras de Kanban',
            },
        ),
        migrations.CreateModel(
            name='RendimentoGrosaPorTamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.PositiveIntegerField(help_text='Tamanho do produto (ex: 14, 16, 18).', unique=True)),
                ('rendimento_grosas_por_placa', models.DecimalField(decimal_places=2, help_text='Quantidade de grosas que uma placa inteira rende para este tamanho.', max_digits=10)),
            ],
            options={
                'verbose_name': 'Rendimento de Grosa por Tamanho',
                'verbose_name_plural': 'Rendimentos de Grosas por Tamanho',
                'ordering': ['tamanho'],
            },
        ),
        migrations.CreateModel(
            name='TransferenciaEntreSetores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_transferido', models.DecimalField(decimal_places=4, max_digits=10)),
                ('data_transferencia', models.DateTimeField(auto_now_add=True)),
                ('ordem_producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='producao.ordemproducao')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.operador')),
                ('setor_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_entrada', to='cadastros.setor')),
                ('setor_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_saida', to='cadastros.setor')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoReposicaoKanban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_placas_solicitada', models.PositiveIntegerField(help_text='Quantidade de placas solicitadas, conforme o cartão Kanban físico.')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_PRODUCAO', 'Em Produção'), ('AGUARDANDO_CORTE', 'Aguardando Corte'), ('AGUARDANDO_PASTILHA', 'Aguardando Medição na Pastilha'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=30)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('item_estoque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_reposicao', to='producao.itemestoquekanban')),
                ('lancamento_cilindro', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacao_kanban_atendida', to='producao.lancamentocilindro')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de Reposição Kanban',
                'verbose_name_plural': 'Solicitações de Reposição Kanban',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoQuimicaKanban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_solicitada', models.DecimalField(decimal_places=2, help_text='Quantidade em grosas que o Torno precisa', max_digits=10)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20)),
                ('data_atendimento', models.DateTimeField(blank=True, help_text='Data e hora em que a Química finalizou a produção', null=True)),
                ('ordem_producao', models.ForeignKey(limit_choices_to={'is_kanban': True}, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_quimica_kanban', to='producao.ordemproducao')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação Química para Kanban',
                'verbose_name_plural': 'Solicitações Químicas para Kanban',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='ReprogramacaoOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reprogramacao', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('peso_reprogramado', models.DecimalField(blank=True, decimal_places=4, help_text='Peso (Kg) a ser reprogramado. Se nulo, reprograma a OP inteira.', max_digits=10, null=True)),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.motivoreprogramacao')),
                ('ordem_producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reprogramacoes', to='producao.ordemproducao')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.operador')),
                ('setor_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.setor')),
            ],
        ),
        migrations.CreateModel(
            name='ParadaPolimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField(blank=True, null=True)),
                ('apontamento_polimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='producao.controlepolimento')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.motivoparada')),
            ],
        ),
        migrations.CreateModel(
            name='ParadaLancamentoAgrupado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracao_minutos', models.PositiveIntegerField()),
                ('lancamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='producao.lancamentocilindro')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.motivoparada')),
            ],
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField(blank=True, null=True)),
                ('apontamento_producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='producao.controleproducaotornolaser')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.motivoparada')),
            ],
        ),
        migrations.CreateModel(
            name='MovimentoEstoqueKanban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimento', models.CharField(choices=[('ENTRADA_PRODUCAO', 'Entrada por Produção'), ('SAIDA_CONSUMO', 'Saída por Consumo em OP'), ('AJUSTE_POSITIVO', 'Ajuste de Inventário (Positivo)'), ('AJUSTE_NEGATIVO', 'Ajuste de Inventário (Negativo)')], max_length=20)),
                ('peso_movimentado_kg', models.DecimalField(decimal_places=4, help_text='Peso em Kg que entrou ou saiu do estoque.', max_digits=10)),
                ('peso_bruto_grosa_no_momento', models.DecimalField(blank=True, decimal_places=6, help_text='Peso bruto por grôsa (em gramas) real, medido no momento da transação.', max_digits=19, null=True)),
                ('grosas_movimentadas', models.DecimalField(decimal_places=2, help_text='Quantidade em grôsas, calculada no momento da transação.', max_digits=10)),
                ('data_movimento', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('item_estoque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='producao.itemestoquekanban')),
                ('ordem_producao_consumo', models.ForeignKey(blank=True, help_text='OP de cliente que consumiu este estoque (para saídas).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='producao.ordemproducao')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.operador')),
                ('solicitacao_atendida', models.ForeignKey(blank=True, help_text='Solicitação de reposição que gerou esta entrada no estoque.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='producao.solicitacaoreposicaokanban')),
            ],
            options={
                'verbose_name': 'Movimento de Estoque Kanban',
                'verbose_name_plural': 'Movimentos de Estoque Kanban',
                'ordering': ['-data_movimento'],
            },
        ),
        migrations.AddField(
            model_name='lancamentocilindro',
            name='solicitacao_reposicao',
            field=models.ForeignKey(blank=True, help_text='Vínculo com a solicitação de reposição Kanban, se aplicável.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_cilindro', to='producao.solicitacaoreposicaokanban'),
        ),
        migrations.CreateModel(
            name='ItemPolimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_carregado', models.DecimalField(decimal_places=3, help_text='Peso (Kg) deste item específico carregado no tambor.', max_digits=10)),
                ('apontamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_no_tambor', to='producao.controlepolimento')),
                ('item_demanda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apontamentos_polimento', to='producao.itemdemandaproducao')),
            ],
            options={
                'unique_together': {('apontamento', 'item_demanda')},
            },
        ),
        migrations.AddField(
            model_name='itemdemandaproducao',
            name='ordem_producao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandas', to='producao.ordemproducao', verbose_name='Lote de Fabricação (OP)'),
        ),
        migrations.AddField(
            model_name='itemdemandaproducao',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='producao.pedido'),
        ),
        migrations.CreateModel(
            name='EstoqueKanban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_peso_kg', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Saldo em Peso (Kg)')),
                ('saldo_grosas_aproximado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo em Grôsas (Aproximado)')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('item_estoque', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='estoque', to='producao.itemestoquekanban')),
            ],
            options={
                'verbose_name': 'Estoque Kanban',
                'verbose_name_plural': 'Estoques Kanban',
            },
        ),
        migrations.CreateModel(
            name='ControleTingimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('ordem_producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_apontamentos', to='producao.ordemproducao')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.operador')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ControleQualidadeEsteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('peso_total_aprovado', models.DecimalField(decimal_places=3, help_text='Peso total dos botões aprovados em Kg', max_digits=10)),
                ('peso_defeito_tipo_a', models.DecimalField(decimal_places=3, default=0, help_text='Peso de defeitos visuais em Kg', max_digits=10)),
                ('peso_defeito_tipo_b', models.DecimalField(decimal_places=3, default=0, help_text='Peso de defeitos de medida em Kg', max_digits=10)),
                ('item_demanda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_apontamentos', to='producao.itemdemandaproducao')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.operador')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='controleproducaotornolaser',
            name='ordem_producao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_apontamentos', to='producao.ordemproducao'),
        ),
        migrations.AddField(
            model_name='controleproducaotornolaser',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.operador'),
        ),
        migrations.AddField(
            model_name='controlepolimento',
            name='itens_demanda_agrupados',
            field=models.ManyToManyField(related_name='apontamentos_polimento_agrupados', through='producao.ItemPolimento', to='producao.itemdemandaproducao'),
        ),
        migrations.AddField(
            model_name='controlepolimento',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.operador'),
        ),
        migrations.AddField(
            model_name='controlepolimento',
            name='tambor',
            field=models.ForeignKey(blank=True, limit_choices_to={'setor__nome': 'POLIMENTO'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.maquina'),
        ),
        migrations.CreateModel(
            name='ControlePastilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('NORMAL', 'Normal'), ('FINA', 'Mais Fina'), ('GROSSA', 'Mais Grossa'), ('REAPROVEITADA', 'Reaproveitada')], max_length=20)),
                ('peso', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quantidade_grosas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ordem_producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_apontamentos', to='producao.ordemproducao')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.operador')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ControleEsteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('quantidade_defeito', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unidade_defeito', models.CharField(choices=[('KG', 'Kg'), ('GROSA', 'Grosa'), ('UN', 'Unidade')], max_length=10)),
                ('ordem_producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_apontamentos', to='producao.ordemproducao')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.operador')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContagemFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('tipo_embalagem', models.CharField(choices=[('NEUTRA', 'Neutra'), ('IMPRESSA', 'Impressa')], max_length=20)),
                ('pesagem', models.CharField(choices=[('G_1', '1 Grosas'), ('G_3', '3 Grosas'), ('G_5', '5 Grosas'), ('G_10', '10 Grosas'), ('KG_PC', 'KG(PÇ)')], max_length=20)),
                ('total_embalagem', models.IntegerField()),
                ('maquina_contagem', models.ForeignKey(limit_choices_to={'tipo': 'CONTAGEM'}, on_delete=django.db.models.deletion.PROTECT, to='cadastros.maquina')),
                ('ordem_producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_apontamentos', to='producao.ordemproducao')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.operador')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConferenciaEscolhaFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('peso_10_botoes', models.DecimalField(decimal_places=3, help_text='Peso de 10 botões em gramas', max_digits=10)),
                ('peso_aferido', models.DecimalField(blank=True, decimal_places=3, default=0.0, help_text='Peso total do lote recebido em Kg', max_digits=10, null=True)),
                ('quantidade_grosas_calculada', models.DecimalField(decimal_places=2, editable=False, help_text='Cálculo automático', max_digits=10)),
                ('item_demanda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_apontamentos', to='producao.itemdemandaproducao')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.operador')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='agrupamentolancamento',
            name='ordens_producao',
            field=models.ManyToManyField(related_name='agrupamentos', to='producao.ordemproducao'),
        ),
        migrations.CreateModel(
            name='Afiacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FERRAMENTA', 'Afiação de Ferramenta'), ('BROCA', 'Afiação de Broca')], max_length=20)),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField(blank=True, null=True)),
                ('apontamento_producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afiacoes', to='producao.controleproducaotornolaser')),
            ],
        ),
        migrations.CreateModel(
            name='SaldoOPSetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_peso', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('ordem_producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_por_setor', to='producao.ordemproducao')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.setor')),
            ],
            options={
                'unique_together': {('ordem_producao', 'setor')},
            },
        ),
        migrations.CreateModel(
            name='LoteQuimico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_programacao', models.DateField(db_index=True, help_text='Data da programação para agrupar as OPs')),
                ('quantidade_total_necessaria', models.DecimalField(decimal_places=4, max_digits=19)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PRODUZIDO', 'Produzido')], default='PENDENTE', max_length=20)),
                ('data_producao', models.DateTimeField(blank=True, help_text='Data/hora em que foi marcado como produzido', null=True)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_produzidos', to='producao.formulaquimica')),
                ('ordens_producao', models.ManyToManyField(related_name='lotes_quimicos_associados', to='producao.ordemproducao')),
            ],
            options={
                'verbose_name': 'Lote Químico',
                'verbose_name_plural': 'Lotes Químicos',
                'unique_together': {('formula', 'data_programacao')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='itemdemandaproducao',
            unique_together={('ordem_producao', 'pedido', 'cor_final', 'item_pedido_erp')},
        ),
        migrations.CreateModel(
            name='FormulaPorCamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camada', models.PositiveIntegerField(help_text='Número da camada (FTD02.FdtItm)')),
                ('porcentagem', models.DecimalField(decimal_places=4, help_text='Porcentagem ou Peso Fixo da camada (FTM05.FtmBPor)', max_digits=10)),
                ('quantidade_fixa', models.BooleanField(default=False, help_text="Peso fixo em vez de percentual? (FTM05.FtmBFix = 'S')")),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.formulaquimica')),
                ('ordem_producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas_por_camada', to='producao.ordemproducao')),
            ],
            options={
                'verbose_name': 'Fórmula por Camada',
                'verbose_name_plural': 'Fórmulas por Camada',
                'ordering': ['camada'],
                'unique_together': {('ordem_producao', 'camada')},
            },
        ),
        migrations.CreateModel(
            name='ContribuicaoOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_placas_contribuida', models.DecimalField(decimal_places=4, help_text='Quantidade de placas que esta OP específica contribuiu neste lançamento.', max_digits=10)),
                ('quantidade_grosas_produzida', models.DecimalField(decimal_places=4, default=0, editable=False, help_text='Quantidade de grosas calculada para esta contribuição.', max_digits=10)),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribuicoes_op', to='producao.lancamentocilindro')),
                ('ordem_producao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contribuicoes_op', to='producao.ordemproducao')),
            ],
            options={
                'verbose_name': 'Contribuição de OP no Lançamento',
                'verbose_name_plural': 'Contribuições de OPs nos Lançamentos',
                'unique_together': {('lancamento', 'ordem_producao')},
            },
        ),
        migrations.CreateModel(
            name='ComponenteFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_sequencia', models.PositiveIntegerField(help_text='Sequência do item na receita do ERP', null=True)),
                ('componente_codigo', models.CharField(db_index=True, help_text='Código da matéria-prima (FTC02.FtcProCod)', max_length=50)),
                ('componente_qtd_base', models.DecimalField(decimal_places=4, help_text='Quantidade do componente para a receita base (FTC02.FtcQtd)', max_digits=19)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='producao.formulaquimica')),
            ],
            options={
                'verbose_name': 'Componente de Fórmula',
                'verbose_name_plural': 'Componentes de Fórmulas',
                'ordering': ['item_sequencia'],
                'unique_together': {('formula', 'componente_codigo')},
            },
        ),
    ]
