# Generated by Django 4.2.21 on 2025-07-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pro01',
            fields=[
                ('procod', models.CharField(db_column='procod', max_length=50, primary_key=True, serialize=False)),
                ('probarttam', models.CharField(db_column='probarttam', max_length=50)),
            ],
            options={
                'db_table': 'pro01',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='tarja',
            field=models.CharField(blank=True, choices=[('AZUL', 'Azul'), ('AMARELO', 'Amarelo'), ('VERMELHO', 'Vermelho'), ('PRETO', 'Preto'), ('VERDE', 'Verde'), ('ROSA', 'Rosa')], help_text='Tarja de prioridade da programação', max_length=20, null=True),
        ),
    ]
