# Generated by Django 4.2.21 on 2025-08-11 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_alter_setor_table'),
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlequalidadeesteira',
            name='maquina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.maquina', verbose_name='Esteira'),
        ),
        migrations.AddField(
            model_name='controlequalidadeesteira',
            name='responsavel_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apontamentos_cq_operador2', to='cadastros.operador', verbose_name='Operador 2 (Opcional)'),
        ),
    ]
