# Generated by Django 4.2.21 on 2025-08-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0002_controlequalidadeesteira_maquina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlequalidadeesteira',
            name='peso_total_aprovado',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Peso total dos botões aprovados em Kg', max_digits=10, null=True),
        ),
    ]
