# Generated by Django 4.2.21 on 2025-07-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0002_pro01_ordemproducao_tarja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivoreprogramacao',
            name='setor_responsavel',
            field=models.CharField(choices=[('QUIMICA', 'Química'), ('PASTILHA', 'Controle de Pastilha'), ('TORNO', 'Torno'), ('LASER', 'Laser'), ('LASER_2', 'Laser 2'), ('POLIMENTO', 'Polimento'), ('TINGIMENTO', 'Tingimento'), ('ESCOLHA_FINAL', 'Escolha Final'), ('CONTAGEM', 'Contagem'), ('ESTEIRA', 'Esteira'), ('KANBAN', 'Kanban'), ('FINALIZADO', 'Finalizado'), ('REPROGRAMADO', 'Reprogramado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='setor_atual',
            field=models.CharField(choices=[('QUIMICA', 'Química'), ('PASTILHA', 'Controle de Pastilha'), ('TORNO', 'Torno'), ('LASER', 'Laser'), ('LASER_2', 'Laser 2'), ('POLIMENTO', 'Polimento'), ('TINGIMENTO', 'Tingimento'), ('ESCOLHA_FINAL', 'Escolha Final'), ('CONTAGEM', 'Contagem'), ('ESTEIRA', 'Esteira'), ('KANBAN', 'Kanban'), ('FINALIZADO', 'Finalizado'), ('REPROGRAMADO', 'Reprogramado')], default='PASTILHA', max_length=50),
        ),
        migrations.AlterField(
            model_name='reprogramacaoop',
            name='setor_origem',
            field=models.CharField(choices=[('QUIMICA', 'Química'), ('PASTILHA', 'Controle de Pastilha'), ('TORNO', 'Torno'), ('LASER', 'Laser'), ('LASER_2', 'Laser 2'), ('POLIMENTO', 'Polimento'), ('TINGIMENTO', 'Tingimento'), ('ESCOLHA_FINAL', 'Escolha Final'), ('CONTAGEM', 'Contagem'), ('ESTEIRA', 'Esteira'), ('KANBAN', 'Kanban'), ('FINALIZADO', 'Finalizado'), ('REPROGRAMADO', 'Reprogramado')], max_length=50),
        ),
    ]
