# Generated by Django 4.2.21 on 2025-07-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0003_alter_motivoreprogramacao_setor_responsavel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ftm04',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftmacod', models.CharField(db_column='FtmAcod', max_length=50)),
                ('ftmeart', models.CharField(db_column='FtmEArt', max_length=255)),
                ('ftmeobs', models.TextField(blank=True, db_column='FtmEObs', null=True)),
            ],
            options={
                'db_table': 'ftm04',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ftm06',
            fields=[
                ('ftmacod', models.CharField(db_column='FtmAcod', max_length=50, primary_key=True, serialize=False)),
                ('ftmhobs', models.TextField(blank=True, db_column='FtmHObs', null=True)),
            ],
            options={
                'db_table': 'ftm06',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='observacao_ficha_tecnica',
            field=models.TextField(blank=True, help_text='Observações da Ficha Técnica (FTM04)', null=True),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='observacao_material',
            field=models.TextField(blank=True, help_text='Observações do Material (FTM06)', null=True),
        ),
    ]
