# Generated by Django 4.2.21 on 2025-08-12 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_alter_setor_table'),
        ('producao', '0003_alter_controlequalidadeesteira_peso_total_aprovado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApontamentoTingimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('cor_final_alvo', models.CharField(help_text='A cor final que este lote de tingimento deve atingir.', max_length=100)),
            ],
            options={
                'verbose_name': 'Apontamento de Tingimento',
                'verbose_name_plural': 'Apontamentos de Tingimento',
                'ordering': ['-data_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ItemTingimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_carregado', models.DecimalField(decimal_places=3, help_text='Peso (Kg) deste item específico carregado para tingimento.', max_digits=10)),
                ('apontamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_no_lote', to='producao.apontamentotingimento')),
                ('item_demanda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apontamentos_tingimento', to='producao.itemdemandaproducao')),
                ('proximo_setor', models.ForeignKey(blank=True, help_text='Destino do item após o tingimento.', limit_choices_to={'nome__in': ['ESCOLHA FINAL', 'TORNO', 'LASER', 'POLIMENTO']}, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.setor')),
            ],
            options={
                'verbose_name': 'Item do Lote de Tingimento',
                'verbose_name_plural': 'Itens nos Lotes de Tingimento',
                'unique_together': {('apontamento', 'item_demanda')},
            },
        ),
        migrations.DeleteModel(
            name='ControleTingimento',
        ),
        migrations.AddField(
            model_name='apontamentotingimento',
            name='itens_demanda',
            field=models.ManyToManyField(related_name='lotes_de_tingimento', through='producao.ItemTingimento', to='producao.itemdemandaproducao'),
        ),
        migrations.AddField(
            model_name='apontamentotingimento',
            name='maquina',
            field=models.ForeignKey(blank=True, limit_choices_to={'setor__nome': 'TINGIMENTO'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.maquina', verbose_name='Máquina de Tingimento'),
        ),
        migrations.AddField(
            model_name='apontamentotingimento',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.operador'),
        ),
    ]
