# Generated by Django 4.2.21 on 2025-08-12 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_alter_setor_table'),
        ('producao', '0004_apontamentotingimento_itemtingimento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentoTingimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lançamento de Tingimento',
                'verbose_name_plural': 'Lançamentos de Tingimento',
                'ordering': ['-data_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ParadaTingimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField(blank=True, null=True)),
                ('lancamento_tingimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='producao.lancamentotingimento')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.motivoparada')),
            ],
        ),
        migrations.CreateModel(
            name='LoteTingimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor_final_alvo', models.CharField(help_text='A cor final que este lote de tingimento deve atingir.', max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='EM_ANDAMENTO', max_length=20)),
                ('observacao_final', models.TextField(blank=True, help_text='Observações gerais ao finalizar o lote.', null=True)),
                ('itens_demanda', models.ManyToManyField(related_name='lotes_de_tingimento', through='producao.ItemTingimento', to='producao.itemdemandaproducao')),
            ],
            options={
                'verbose_name': 'Lote de Tingimento',
                'verbose_name_plural': 'Lotes de Tingimento',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddField(
            model_name='lancamentotingimento',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='producao.lotetingimento'),
        ),
        migrations.AddField(
            model_name='lancamentotingimento',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.maquina', verbose_name='Máquina de Tingimento'),
        ),
        migrations.AddField(
            model_name='lancamentotingimento',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.operador'),
        ),
        migrations.AlterUniqueTogether(
            name='itemtingimento',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='itemtingimento',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_no_lote', to='producao.lotetingimento'),
        ),
        migrations.AlterUniqueTogether(
            name='itemtingimento',
            unique_together={('lote', 'item_demanda')},
        ),
        migrations.RemoveField(
            model_name='itemtingimento',
            name='apontamento',
        ),
        migrations.DeleteModel(
            name='ApontamentoTingimento',
        ),
    ]
