# Generated by Django 4.2.21 on 2025-07-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0004_ftm04_ftm06_ordemproducao_observacao_ficha_tecnica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdv06',
            fields=[
                ('pdvempcod', models.CharField(db_column='pdvempcod', max_length=10)),
                ('pdvcod', models.CharField(db_column='pdvcod', max_length=50, primary_key=True, serialize=False)),
                ('pdvobsdet', models.TextField(blank=True, db_column='PdvObsDet', null=True)),
            ],
            options={
                'db_table': 'pdv06',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='observacao_pedido_venda',
            field=models.TextField(blank=True, help_text='Observações do Pedido de Venda (PDV06)', null=True),
        ),
    ]
