# Generated by Django 4.2.21 on 2025-07-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0005_pdv06_ordemproducao_observacao_pedido_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='observacao_op',
            field=models.TextField(blank=True, help_text='Observações gerais da OP (PCP)', null=True),
        ),
    ]
