# Generated by Django 4.2.21 on 2025-08-12 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0005_lancamentotingimento_paradatingimento_lotetingimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lancamentotingimento',
            name='maquina',
        ),
    ]
