# Generated by Django 4.2.21 on 2025-08-12 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0006_remove_lancamentotingimento_maquina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtingimento',
            name='peso_carregado',
        ),
        migrations.AlterField(
            model_name='itemtingimento',
            name='lote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_no_lote', to='producao.lotetingimento'),
        ),
        migrations.CreateModel(
            name='CargaLancamentoTingimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_carregado', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('item_tingimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas', to='producao.itemtingimento')),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas', to='producao.lancamentotingimento')),
            ],
            options={
                'verbose_name': 'Carga de Lançamento de Tingimento',
                'verbose_name_plural': 'Cargas de Lançamentos de Tingimento',
                'unique_together': {('lancamento', 'item_tingimento')},
            },
        ),
    ]
