# Generated by Django 4.2.21 on 2025-07-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0006_ordemproducao_observacao_op'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='preco_venda',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Preço de Venda do item no Pedido (PdvPrcVen)', max_digits=19, null=True),
        ),
    ]
