# Generated by Django 4.2.21 on 2025-07-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0007_ordemproducao_preco_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='numero_agrupamento',
            field=models.CharField(blank=True, help_text='Código de Agrupamento da OP (OprAAgr)', max_length=50, null=True),
        ),
    ]
