# Generated by Django 4.2.21 on 2025-07-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0008_ordemproducao_numero_agrupamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ftc01',
            fields=[
                ('ftcacod', models.CharField(db_column='FtcACod', max_length=50, primary_key=True, serialize=False)),
                ('ftcanom', models.CharField(db_column='FtcANom', max_length=255)),
            ],
            options={
                'db_table': 'ftc01',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ftd02',
            fields=[
                ('ftdsequencia', models.IntegerField(db_column='FtdSequencia', primary_key=True, serialize=False)),
                ('gddcod', models.CharField(db_column='GddCod', max_length=50)),
                ('ftcacod', models.CharField(db_column='FtcACod', max_length=50)),
            ],
            options={
                'db_table': 'ftd02',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='peso_placa',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Peso da Placa (OPRAPESCJT)', max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='peso_previsto',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Peso Previsto (OPRAPESPRV)', max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='quantidade_placas',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Quantidade de Placas (OPRAQTDCJT)', max_digits=19, null=True),
        ),
    ]
