# Generated by Django 4.2.21 on 2025-08-12 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_alter_setor_table'),
        ('producao', '0008_remove_itemtingimento_proximo_setor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargalancamentotingimento',
            name='proximo_setor',
        ),
        migrations.AddField(
            model_name='itemtingimento',
            name='proximo_setor',
            field=models.ForeignKey(blank=True, help_text='Destino do item após o tingimento.', limit_choices_to={'nome__in': ['ESCOLHA FINAL', 'TORNO', 'LASER', 'POLIMENTO']}, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.setor'),
        ),
    ]
