# Generated by Django 4.2.21 on 2025-07-04 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0009_ftc01_ftd02_ordemproducao_peso_placa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ftc02',
            fields=[
                ('ftcacod', models.CharField(db_column='FtcACod', help_text='Código da Fórmula', max_length=50, primary_key=True, serialize=False)),
                ('ftcprocod', models.CharField(db_column='FtcProCod', help_text='Código do Produto (Componente)', max_length=50)),
                ('ftcqtd', models.DecimalField(db_column='FtcQtd', decimal_places=4, help_text='Quantidade do Componente na base', max_digits=19)),
            ],
            options={
                'db_table': 'ftc02',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FormulaQuimica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_formula', models.CharField(db_index=True, help_text='Código da Fórmula (FTC01.FtcACod)', max_length=50, unique=True)),
                ('nome_formula', models.CharField(help_text='Nome descritivo da fórmula (FTC01.FtcANom)', max_length=255)),
                ('formula_qtd_base', models.DecimalField(decimal_places=4, help_text='Quantidade base da receita em gramas (FTC01.FtcAQtdBas)', max_digits=19)),
            ],
            options={
                'verbose_name': 'Fórmula Química',
                'verbose_name_plural': 'Fórmulas Químicas',
            },
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='formula_quimica',
            field=models.ForeignKey(blank=True, help_text='Fórmula química associada a esta OP', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_producao', to='producao.formulaquimica'),
        ),
        migrations.CreateModel(
            name='ComponenteFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente_codigo', models.CharField(db_index=True, help_text='Código da matéria-prima (FTC02.FtcProCod)', max_length=50)),
                ('componente_qtd_base', models.DecimalField(decimal_places=4, help_text='Quantidade do componente para a receita base (FTC02.FtcQtd)', max_digits=19)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='producao.formulaquimica')),
            ],
            options={
                'verbose_name': 'Componente de Fórmula',
                'verbose_name_plural': 'Componentes de Fórmulas',
                'unique_together': {('formula', 'componente_codigo')},
            },
        ),
    ]
