# Generated by Django 4.2.21 on 2025-08-12 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_alter_setor_table'),
        ('producao', '0009_remove_cargalancamentotingimento_proximo_setor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contagemfinal',
            name='maquina_contagem',
            field=models.ForeignKey(blank=True, limit_choices_to={'setor__nome': 'ESCOLHA FINAL'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.maquina'),
        ),
        migrations.AlterField(
            model_name='motivoreprogramacao',
            name='setor_responsavel',
            field=models.CharField(choices=[('QUIMICA', 'Química'), ('PASTILHA', 'Controle de Pastilha'), ('TORNOS', 'Tornos'), ('LASER', 'Laser'), ('LASER_2', 'Laser 2'), ('POLIMENTO', 'Polimento'), ('TINGIMENTO', 'Tingimento'), ('ESCOLHA_FINAL', 'Escolha Final'), ('CONTAGEM', 'Contagem'), ('ESTEIRA', 'Esteira'), ('KANBAN', 'Kanban'), ('FINALIZADO', 'Finalizado'), ('REPROGRAMADO', 'Reprogramado')], max_length=50),
        ),
        migrations.CreateModel(
            name='SaldoItemEmbalagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_grosas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('item_demanda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saldo_embalagem', to='producao.itemdemandaproducao')),
            ],
        ),
        migrations.CreateModel(
            name='ApontamentoEmbalagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_embalada', models.DecimalField(decimal_places=2, help_text='Quantidade em Grosas', max_digits=10)),
                ('numero_caixa', models.PositiveIntegerField()),
                ('tam_cx', models.CharField(choices=[('1', 'Tamanho 1'), ('2', 'Tamanho 2'), ('3', 'Tamanho 3'), ('4', 'Tamanho 4')], max_length=2, verbose_name='Tamanho da Caixa')),
                ('tipo_caixa', models.CharField(choices=[('LISA', 'Lisa'), ('IMPRESSA', 'Impressa')], default='LISA', max_length=10)),
                ('peso_caixa', models.DecimalField(decimal_places=3, help_text='Peso final da caixa em Kg', max_digits=10)),
                ('data_apontamento', models.DateTimeField(auto_now_add=True)),
                ('item_demanda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apontamentos_embalagem', to='producao.itemdemandaproducao')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.operador')),
            ],
            options={
                'verbose_name': 'Apontamento de Embalagem',
                'verbose_name_plural': 'Apontamentos de Embalagem',
                'ordering': ['item_demanda__pedido', 'numero_caixa'],
            },
        ),
    ]
