# Generated by Django 4.2.21 on 2025-08-14 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_alter_setor_table'),
        ('producao', '0010_alter_contagemfinal_maquina_contagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Nº da Caixa')),
                ('status', models.CharField(choices=[('EM_EMBALAGEM', 'Em Embalagem'), ('AGUARDANDO_CONFERENCIA', 'Aguardando Conferência'), ('CONFERIDA', 'Conferida'), ('EM_REMESSA', 'Em Remessa')], default='EM_EMBALAGEM', max_length=30)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('tam_cx', models.CharField(choices=[('1', 'Tamanho 1'), ('2', 'Tamanho 2'), ('3', 'Tamanho 3'), ('4', 'Tamanho 4')], max_length=2, verbose_name='Tamanho da Caixa')),
                ('tipo_caixa', models.CharField(choices=[('LISA', 'Lisa'), ('IMPRESSA', 'Impressa')], max_length=10)),
                ('peso_final_caixa', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('data_conferencia', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Caixa de Embalagem',
                'verbose_name_plural': 'Caixas de Embalagem',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cliente', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Fantasia')),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF/CNPJ')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_representante', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Representante',
                'verbose_name_plural': 'Representantes',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cliente_codigo',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cliente_nome',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='representante',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='representante_codigo',
        ),
        migrations.CreateModel(
            name='Remessa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Nº da Remessa')),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('EM_ABERTO', 'Em Aberto'), ('ENVIADA', 'Enviada')], default='EM_ABERTO', max_length=20)),
                ('caixas', models.ManyToManyField(help_text='Caixas incluídas neste envio.', related_name='remessas', to='producao.caixa')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remessas', to='producao.cliente')),
            ],
            options={
                'verbose_name': 'Remessa de Expedição',
                'verbose_name_plural': 'Remessas de Expedição',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='representante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='producao.representante'),
        ),
        migrations.AddField(
            model_name='caixa',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caixas', to='producao.cliente'),
        ),
        migrations.AddField(
            model_name='caixa',
            name='responsavel_embalagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='caixas_embaladas', to='cadastros.operador'),
        ),
        migrations.AddField(
            model_name='caixa',
            name='responsavel_expedicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='caixas_conferidas', to='cadastros.operador'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='producao.cliente'),
        ),
        migrations.CreateModel(
            name='ItemCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_embalada', models.DecimalField(decimal_places=2, help_text='Quantidade em Grosas', max_digits=10)),
                ('conferido_expedicao', models.BooleanField(default=False)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_na_caixa', to='producao.caixa')),
                ('item_demanda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_em_caixas', to='producao.itemdemandaproducao')),
            ],
            options={
                'verbose_name': 'Item na Caixa',
                'verbose_name_plural': 'Itens na Caixa',
                'unique_together': {('caixa', 'item_demanda')},
            },
        ),
    ]
