# Generated by Django 4.2.21 on 2025-07-07 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0010_ftc02_formulaquimica_ordemproducao_formula_quimica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulaquimica',
            name='formula_qtd_base',
        ),
    ]
