# Generated by Django 4.2.21 on 2025-08-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0011_caixa_cliente_representante_remove_pedido_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenciaescolhafinal',
            name='espessura_conferida',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Espessura em mm conferida pela operadora.', max_digits=10, null=True),
        ),
    ]
