# Generated by Django 4.2.21 on 2025-07-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0011_remove_formulaquimica_formula_qtd_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='aproveitamento',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentual de Aproveitamento (FtmDApr)', max_digits=10, null=True),
        ),
    ]
