# Generated by Django 4.2.21 on 2025-08-18 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_alter_setor_table'),
        ('producao', '0012_conferenciaescolhafinal_espessura_conferida'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenciaCaixaExpedicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_caixa', models.PositiveIntegerField()),
                ('peso_conferido', models.DecimalField(blank=True, decimal_places=3, help_text='Peso final da caixa em Kg', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_CONFERENCIA', 'Em Conferência'), ('FINALIZADA', 'Finalizada')], default='PENDENTE', max_length=20)),
                ('data_inicio_conferencia', models.DateTimeField(blank=True, null=True)),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferencias_caixa', to='producao.pedido')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.operador')),
            ],
            options={
                'verbose_name': 'Conferência de Caixa para Expedição',
                'verbose_name_plural': 'Conferências de Caixas para Expedição',
                'ordering': ['pedido', 'numero_caixa'],
                'unique_together': {('pedido', 'numero_caixa')},
            },
        ),
        migrations.CreateModel(
            name='ItemConferenciaCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conferido', models.BooleanField(default=False)),
                ('apontamento_embalagem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='item_conferido', to='producao.apontamentoembalagem')),
                ('conferencia_caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_conferidos', to='producao.conferenciacaixaexpedicao')),
            ],
        ),
    ]
