# Generated by Django 4.2.21 on 2025-07-07 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0012_ordemproducao_aproveitamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ftm05',
            fields=[
                ('ftmacod', models.CharField(db_column='FtmACod', max_length=50, primary_key=True, serialize=False)),
                ('ftmbitm', models.IntegerField(db_column='FtmBItm', help_text='Número do Item / Camada')),
                ('ftmbpor', models.DecimalField(db_column='FtmBPor', decimal_places=4, help_text='Valor (Peso Fixo ou Percentual)', max_digits=19)),
                ('ftmbfix', models.CharField(db_column='FtmBFix', help_text='Flag de Quantidade Fixa (S/N)', max_length=1)),
            ],
            options={
                'db_table': 'ftm05',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='ordemproducao',
            name='formula_quimica',
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='peso_placa',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Peso da Placa para base da receita (OPRAPESCJT)', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='peso_previsto',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Peso Previsto TOTAL da OP (OPRAPESPRV)', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='quantidade_placas',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Quantidade de Camadas (de FTM01.FtmACam ou OPR01.OprAQtdCjt)', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='setor_atual',
            field=models.CharField(choices=[('QUIMICA', 'Química'), ('PASTILHA', 'Controle de Pastilha'), ('TORNO', 'Torno'), ('LASER', 'Laser'), ('LASER_2', 'Laser 2'), ('POLIMENTO', 'Polimento'), ('TINGIMENTO', 'Tingimento'), ('ESCOLHA_FINAL', 'Escolha Final'), ('CONTAGEM', 'Contagem'), ('ESTEIRA', 'Esteira'), ('KANBAN', 'Kanban'), ('FINALIZADO', 'Finalizado'), ('REPROGRAMADO', 'Reprogramado')], default='QUIMICA', max_length=50),
        ),
        migrations.CreateModel(
            name='FormulaPorCamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camada', models.PositiveIntegerField(help_text='Número da camada (FTD02.RdtItm)')),
                ('porcentagem', models.DecimalField(decimal_places=4, help_text='Porcentagem ou Peso Fixo da camada (FTM05.FtmBPor)', max_digits=10)),
                ('quantidade_fixa', models.BooleanField(default=False, help_text="Peso fixo em vez de percentual? (FTM05.FtmBFix = 'S')")),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.formulaquimica')),
                ('ordem_producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas_por_camada', to='producao.ordemproducao')),
            ],
            options={
                'verbose_name': 'Fórmula por Camada',
                'verbose_name_plural': 'Fórmulas por Camada',
                'ordering': ['camada'],
                'unique_together': {('ordem_producao', 'camada')},
            },
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='formulas',
            field=models.ManyToManyField(help_text='Fórmulas químicas para cada camada da OP', related_name='ordens_producao', through='producao.FormulaPorCamada', to='producao.formulaquimica'),
        ),
    ]
