# Generated by Django 4.2.21 on 2025-07-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0013_ftm05_remove_ordemproducao_formula_quimica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaporcamada',
            name='camada',
            field=models.PositiveIntegerField(help_text='Número da camada (FTD02.FdtItm)'),
        ),
    ]
