# Generated by Django 4.2.21 on 2025-07-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0015_alter_formulaporcamada_camada'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='rendimento',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Rendimento em grosas por placa (FtmDRen)', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='formulaporcamada',
            name='camada',
            field=models.PositiveIntegerField(help_text='Número da camada (FTD02.FdtItm)'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='formulas',
            field=models.ManyToManyField(related_name='ordens_producao', through='producao.FormulaPorCamada', to='producao.formulaquimica'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='observacao_ficha_tecnica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='observacao_material',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='observacao_op',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='observacao_pedido_venda',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='quantidade_placas',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Quantidade de Camadas', max_digits=19, null=True),
        ),
    ]
