# Generated by Django 4.2.21 on 2025-07-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0016_ordemproducao_rendimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componenteformula',
            name='item_sequencia',
            field=models.PositiveIntegerField(help_text='Sequência do item na receita do ERP', null=True),
        ),
        migrations.AlterField(
            model_name='controleproducaotornolaser',
            name='check_abertura',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='controleproducaotornolaser',
            name='check_broca',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='controleproducaotornolaser',
            name='check_espessura_cabecote1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='controleproducaotornolaser',
            name='check_espessura_cabecote2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
