# Generated by Django 4.2.21 on 2025-07-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0017_componenteformula_item_sequencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teq01',
            fields=[
                ('teqcod', models.CharField(db_column='TeqCod', max_length=50, primary_key=True, serialize=False)),
                ('teqnom', models.CharField(db_column='TeqNom', max_length=255)),
                ('mstcod', models.CharField(db_column='MstCod', max_length=10)),
            ],
            options={
                'db_table': 'teq01',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='componenteformula',
            options={'ordering': ['item_sequencia'], 'verbose_name': 'Componente de Fórmula', 'verbose_name_plural': 'Componentes de Fórmulas'},
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='nome_equipamento',
            field=models.CharField(blank=True, help_text='Nome do equipamento (TEQ01.TeqNom)', max_length=255, null=True),
        ),
    ]
