# Generated by Django 4.2.21 on 2025-07-11 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_operador_setor'),
        ('producao', '0018_teq01_alter_componenteformula_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemproducao',
            name='formulas',
        ),
        migrations.AlterField(
            model_name='contagemfinal',
            name='data_hora_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='controleesteira',
            name='data_hora_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='controlepastilha',
            name='data_hora_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='controlepolimento',
            name='data_hora_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='controleproducaotornolaser',
            name='data_hora_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='controletingimento',
            name='data_hora_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='escolhafinal',
            name='data_hora_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='setor_atual',
            field=models.CharField(choices=[('QUIMICA', 'Química'), ('PASTILHA', 'Controle de Pastilha'), ('TORNO', 'Torno'), ('LASER', 'Laser'), ('LASER_2', 'Laser 2'), ('POLIMENTO', 'Polimento'), ('TINGIMENTO', 'Tingimento'), ('ESCOLHA_FINAL', 'Escolha Final'), ('CONTAGEM', 'Contagem'), ('ESTEIRA', 'Esteira'), ('KANBAN', 'Kanban'), ('FINALIZADO', 'Finalizado'), ('REPROGRAMADO', 'Reprogramado')], default='QUIMICA', max_length=50, verbose_name='Setor Atual'),
        ),
        migrations.CreateModel(
            name='ApontamentoProducaoPlaca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('numero_cilindro', models.PositiveIntegerField()),
                ('borracha_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Centímetros da fração de placa, se houver (fração * 57cm)', max_digits=10, null=True)),
                ('quantidade_grosas_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_placas_total', models.DecimalField(decimal_places=4, max_digits=19)),
                ('ordens_producao_agrupadas', models.ManyToManyField(related_name='%(class)s_apontamentos', to='producao.ordemproducao')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.operador')),
            ],
            options={
                'verbose_name': 'Apontamento de Produção de Placa',
                'verbose_name_plural': 'Apontamentos de Produção de Placas',
                'ordering': ['-data_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='LoteQuimico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_programacao', models.DateField(db_index=True, help_text='Data da programação para agrupar as OPs')),
                ('quantidade_total_necessaria', models.DecimalField(decimal_places=4, max_digits=19)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PRODUZIDO', 'Produzido')], default='PENDENTE', max_length=20)),
                ('data_producao', models.DateTimeField(blank=True, help_text='Data/hora em que foi marcado como produzido', null=True)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_produzidos', to='producao.formulaquimica')),
                ('ordens_producao', models.ManyToManyField(related_name='lotes_quimicos_associados', to='producao.ordemproducao')),
            ],
            options={
                'verbose_name': 'Lote Químico',
                'verbose_name_plural': 'Lotes Químicos',
                'unique_together': {('formula', 'data_programacao')},
            },
        ),
    ]
