# Generated by Django 4.2.21 on 2025-07-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0019_remove_ordemproducao_formulas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='artigo_base',
            field=models.CharField(blank=True, db_index=True, help_text='Código do artigo base (ProBArtCodBas) para conciliação', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='data_qmc',
            field=models.DateField(blank=True, db_index=True, help_text='Data de produção da Química definida na planilha do PCP (DATA_QMC)', null=True),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='sequencia_pcp',
            field=models.IntegerField(blank=True, db_index=True, help_text='Ordem da sequência de produção definida na planilha do PCP (NOVA_SEQ)', null=True),
        ),
    ]
