# Generated by Django 4.2.21 on 2025-07-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0020_ordemproducao_artigo_base_ordemproducao_data_qmc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='cor_pedido',
            field=models.CharField(blank=True, help_text='Cor final do pedido do cliente (PDV02.pdvgddcod1)', max_length=100, null=True),
        ),
    ]
