# Generated by Django 4.2.21 on 2025-07-14 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibgcontrole', '0002_itemprogramacao_ordens_de_producao'),
        ('producao', '0021_ordemproducao_cor_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemproducao',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='ordemproducao',
            name='cor_pedido',
        ),
        migrations.RemoveField(
            model_name='ordemproducao',
            name='numero_pedido',
        ),
        migrations.RemoveField(
            model_name='ordemproducao',
            name='preco_venda',
        ),
        migrations.RemoveField(
            model_name='ordemproducao',
            name='quantidade_pedido',
        ),
        migrations.RemoveField(
            model_name='ordemproducao',
            name='quantidade_programada',
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='quantidade_programada_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Soma das quantidades de todas as demandas do lote.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='cor',
            field=models.CharField(help_text='Cor base da matéria-prima (OPR01.opragddcod1)', max_length=100),
        ),
        migrations.CreateModel(
            name='ItemDemandaProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(db_index=True, help_text='Código do Pedido (PDV02.pdvcod)', max_length=50)),
                ('cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('cor_final', models.CharField(help_text='Cor final do tingimento (PDV02.pdvgddcod1)', max_length=100)),
                ('quantidade', models.DecimalField(decimal_places=2, help_text='Quantidade desta demanda específica (PDV02.pdvqtdpro)', max_digits=10)),
                ('preco_venda', models.DecimalField(blank=True, decimal_places=4, help_text='Preço de Venda do item no Pedido (PDV02.PdvPrcVen)', max_digits=19, null=True)),
                ('status_item', models.CharField(choices=[('AGUARDANDO_PRODUCAO', 'Aguardando Produção'), ('AGUARDANDO_TINGIMENTO', 'Aguardando Tingimento'), ('EM_TINGIMENTO', 'Em Tingimento'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO_PRODUCAO', max_length=50, verbose_name='Status da Demanda')),
                ('item_programacao', models.OneToOneField(blank=True, help_text='Vínculo com o item da planilha de programação do PCP.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demanda_producao_vinculada', to='ibgcontrole.itemprogramacao')),
                ('ordem_producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandas', to='producao.ordemproducao', verbose_name='Lote de Fabricação (OP)')),
            ],
            options={
                'verbose_name': 'Item de Demanda de Produção',
                'verbose_name_plural': 'Itens de Demanda de Produção',
                'ordering': ['ordem_producao', 'numero_pedido'],
                'unique_together': {('ordem_producao', 'numero_pedido', 'cor_final')},
            },
        ),
    ]
