# Generated by Django 4.2.21 on 2025-07-14 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibgcontrole', '0002_itemprogramacao_ordens_de_producao'),
        ('producao', '0022_remove_ordemproducao_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdemandaproducao',
            name='item_programacao',
            field=models.ForeignKey(blank=True, help_text='Vínculo com o item da planilha de programação do PCP. Múltiplas demandas podem se vincular a um item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandas_vinculadas', to='ibgcontrole.itemprogramacao'),
        ),
    ]
