# Generated by Django 4.2.21 on 2025-07-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0023_alter_itemdemandaproducao_item_programacao'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemdemandaproducao',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='itemdemandaproducao',
            name='item_pedido_erp',
            field=models.CharField(blank=True, help_text='Número do item original do pedido no ERP (PDV02.pdvitmpro)', max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='itemdemandaproducao',
            unique_together={('ordem_producao', 'numero_pedido', 'cor_final', 'item_pedido_erp')},
        ),
    ]
