# Generated by Django 4.2.21 on 2025-07-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0024_alter_itemdemandaproducao_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdemandaproducao',
            name='codigo_cliente',
            field=models.CharField(blank=True, db_index=True, help_text='Código do Cliente no ERP (PDV01.pdvterdoc)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itemdemandaproducao',
            name='data_emissao',
            field=models.DateField(blank=True, help_text='Data de Emissão do Pedido (PDV02.pdvemipro)', null=True),
        ),
        migrations.AddField(
            model_name='itemdemandaproducao',
            name='data_entrega',
            field=models.DateField(blank=True, help_text='Data de Entrega Prevista (PDV02.pdvprvent)', null=True),
        ),
    ]
