# Generated by Django 4.2.21 on 2025-07-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0025_itemdemandaproducao_codigo_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdemandaproducao',
            name='quantidade_producao',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantidade de Produção para cálculo financeiro (PDV02.pdvqtdpro)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='itemdemandaproducao',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, help_text='Quantidade desta demanda específica (PDV02.pdvboriproqtd)', max_digits=10),
        ),
    ]
