# Generated by Django 4.2.21 on 2025-07-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0026_itemdemandaproducao_quantidade_producao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdemandaproducao',
            name='observacao_pcp',
            field=models.TextField(blank=True, null=True, verbose_name='Observação do PCP'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='status',
            field=models.CharField(choices=[('PENDENTE_CONFERENCIA', 'Pendente de Conferência PCP'), ('PENDENTE', 'Pendente'), ('EM_PRODUCAO', 'Em Produção'), ('PAUSADO', 'Pausado'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado'), ('REPROGRAMADO', 'Reprogramado')], default='PENDENTE', max_length=50),
        ),
    ]
