# Generated by Django 4.2.21 on 2025-07-18 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producao', '0027_itemdemandaproducao_observacao_pcp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cid01',
            fields=[
                ('cidcod', models.CharField(db_column='CidCod', max_length=50, primary_key=True, serialize=False)),
                ('cidnom', models.CharField(db_column='CidNom', max_length=255)),
                ('estcod', models.CharField(db_column='EstCod', max_length=2)),
            ],
            options={
                'db_table': 'cid01',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rep01',
            fields=[
                ('repdoc', models.CharField(db_column='RepDoc', max_length=50, primary_key=True, serialize=False)),
                ('repnom', models.CharField(db_column='RepNom', max_length=255)),
            ],
            options={
                'db_table': 'rep01',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ter01',
            fields=[
                ('terdoc', models.CharField(db_column='TerDoc', max_length=50, primary_key=True, serialize=False)),
                ('ternom', models.CharField(db_column='TerNom', max_length=255)),
            ],
            options={
                'db_table': 'ter01',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(db_index=True, max_length=50, unique=True)),
                ('cliente_nome', models.CharField(max_length=255)),
                ('cliente_codigo', models.CharField(db_index=True, max_length=50)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('representante', models.CharField(blank=True, max_length=100, null=True)),
                ('representante_codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('data_emissao', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pedido de Venda',
                'verbose_name_plural': 'Pedidos de Venda',
                'ordering': ['-data_emissao', '-numero_pedido'],
            },
        ),
        migrations.AlterModelOptions(
            name='itemdemandaproducao',
            options={'ordering': ['ordem_producao', 'pedido'], 'verbose_name': 'Item de Demanda de Produção', 'verbose_name_plural': 'Itens de Demanda de Produção'},
        ),
        migrations.AddField(
            model_name='itemdemandaproducao',
            name='conferido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Conferido em'),
        ),
        migrations.AddField(
            model_name='itemdemandaproducao',
            name='conferido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Conferido por'),
        ),
        migrations.AddField(
            model_name='itemdemandaproducao',
            name='numero_pedido_cliente',
            field=models.CharField(blank=True, help_text='Número do pedido do cliente (Ex: 006/25)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='status',
            field=models.CharField(choices=[('PENDENTE_CONFERENCIA', 'Pendente de Conferência PCP'), ('PENDENTE', 'Pendente'), ('EM_PRODUCAO', 'Em Produção'), ('PAUSADO', 'Pausado'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado'), ('REPROGRAMADO', 'Reprogramado')], default='PENDENTE_CONFERENCIA', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='itemdemandaproducao',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='itemdemandaproducao',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='producao.pedido'),
        ),
        migrations.AlterUniqueTogether(
            name='itemdemandaproducao',
            unique_together={('ordem_producao', 'pedido', 'cor_final', 'item_pedido_erp')},
        ),
        migrations.RemoveField(
            model_name='itemdemandaproducao',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='itemdemandaproducao',
            name='codigo_cliente',
        ),
        migrations.RemoveField(
            model_name='itemdemandaproducao',
            name='data_emissao',
        ),
        migrations.RemoveField(
            model_name='itemdemandaproducao',
            name='numero_pedido',
        ),
    ]
