# Generated by Django 4.2.21 on 2025-07-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0028_cid01_rep01_ter01_pedido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emb01',
            fields=[
                ('embcod', models.CharField(db_column='EmbCod', max_length=50, primary_key=True, serialize=False)),
                ('embnom', models.CharField(db_column='EmbNom', max_length=255)),
            ],
            options={
                'db_table': 'emb01',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='itemdemandaproducao',
            name='unidade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
