# Generated by Django 4.2.21 on 2025-07-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0029_emb01_itemdemandaproducao_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdemandaproducao',
            name='embalagem',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
