# Generated by Django 4.2.21 on 2025-07-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0030_itemdemandaproducao_embalagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='observacao_detalhada',
            field=models.TextField(blank=True, null=True, verbose_name='Observação Detalhada do Pedido'),
        ),
    ]
