# Generated by Django 4.2.21 on 2025-07-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0031_pedido_observacao_detalhada'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdemandaproducao',
            name='observacao_item_pedido',
            field=models.TextField(blank=True, null=True, verbose_name='Observação (Item do Pedido)'),
        ),
    ]
