# Generated by Django 4.2.21 on 2025-07-23 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producao', '0032_itemdemandaproducao_observacao_item_pedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regrakanban',
            options={'verbose_name': 'Regra de Kanban', 'verbose_name_plural': 'Regras de Kanban'},
        ),
        migrations.AlterUniqueTogether(
            name='regrakanban',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='is_kanban',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica se a OP segue o fluxo contínuo Kanban'),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='requer_tingimento',
            field=models.BooleanField(default=False, help_text='Indica se o produto (Kanban ou não) passará pelo processo de tingimento'),
        ),
        migrations.AddField(
            model_name='regrakanban',
            name='cor_base_neutra',
            field=models.CharField(help_text="A cor base 'neutra' para este material (ex: 200, 100, 500)", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='regrakanban',
            name='material_codigo_erp',
            field=models.CharField(help_text='Código do material no ERP (ex: 9, 28, 8)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='regrakanban',
            name='material_nome',
            field=models.CharField(help_text='Nome do material (ex: Sumatra, PEC)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='data_qmc',
            field=models.DateField(blank=True, db_index=True, help_text='Data de produção da Química importada da planilha do PCP (mantém a primeira ocorrência)', null=True),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='sequencia_pcp',
            field=models.IntegerField(blank=True, db_index=True, help_text='Ordem da sequência de produção importada da planilha do PCP (mantém a primeira ocorrência)', null=True),
        ),
        migrations.AlterField(
            model_name='regrakanban',
            name='artigo',
            field=models.CharField(help_text='Código do Artigo que pode ser Kanban', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='SolicitacaoQuimicaKanban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_solicitada', models.DecimalField(decimal_places=2, help_text='Quantidade em grosas que o Torno precisa', max_digits=10)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20)),
                ('data_atendimento', models.DateTimeField(blank=True, help_text='Data e hora em que a Química finalizou a produção', null=True)),
                ('ordem_producao', models.ForeignKey(limit_choices_to={'eh_kanban': True}, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_quimica_kanban', to='producao.ordemproducao')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação Química para Kanban',
                'verbose_name_plural': 'Solicitações Químicas para Kanban',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.RemoveField(
            model_name='regrakanban',
            name='material',
        ),
    ]
