# Generated by Django 4.2.21 on 2025-07-24 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_alter_maquina_options_remove_maquina_ano_and_more'),
        ('producao', '0033_alter_regrakanban_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApontamentoLancamentoAgrupado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_placas_total', models.DecimalField(decimal_places=4, help_text='Soma total de placas produzidas neste lançamento.', max_digits=10)),
                ('quantidade_grosas_total', models.DecimalField(decimal_places=4, default=0, help_text='Soma total de grosas produzidas. Calculado automaticamente.', max_digits=10)),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.maquina', verbose_name='Cilindro')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.operador')),
            ],
            options={
                'verbose_name': 'Apontamento de Lançamento Agrupado',
                'verbose_name_plural': 'Apontamentos de Lançamentos Agrupados',
                'ordering': ['-data_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ContribuicaoOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_placas_contribuida', models.DecimalField(decimal_places=4, help_text='Quantidade de placas que esta OP específica contribuiu.', max_digits=10)),
                ('quantidade_grosas_produzida', models.DecimalField(decimal_places=4, default=0, editable=False, help_text='Quantidade de grosas calculada para esta contribuição.', max_digits=10)),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.apontamentolancamentoagrupado')),
                ('ordem_producao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.ordemproducao')),
            ],
            options={
                'verbose_name': 'Contribuição de OP',
                'verbose_name_plural': 'Contribuições de OPs',
                'unique_together': {('lancamento', 'ordem_producao')},
            },
        ),
        migrations.CreateModel(
            name='ParadaLancamentoAgrupado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracao_minutos', models.PositiveIntegerField()),
                ('lancamento_agrupado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='producao.apontamentolancamentoagrupado')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.motivoparada')),
            ],
        ),
        migrations.CreateModel(
            name='RendimentoGrosaPorTamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.PositiveIntegerField(help_text='Tamanho do produto (ex: 14, 16, 18).', unique=True)),
                ('rendimento_grosas_por_placa', models.DecimalField(decimal_places=2, help_text='Quantidade de grosas que uma placa inteira rende para este tamanho.', max_digits=10)),
            ],
            options={
                'verbose_name': 'Rendimento de Grosa por Tamanho',
                'verbose_name_plural': 'Rendimentos de Grosas por Tamanho',
                'ordering': ['tamanho'],
            },
        ),
        migrations.AlterField(
            model_name='solicitacaoquimicakanban',
            name='ordem_producao',
            field=models.ForeignKey(limit_choices_to={'is_kanban': True}, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_quimica_kanban', to='producao.ordemproducao'),
        ),
        migrations.DeleteModel(
            name='ApontamentoProducaoPlaca',
        ),
        migrations.AddField(
            model_name='apontamentolancamentoagrupado',
            name='ordens_producao',
            field=models.ManyToManyField(related_name='lancamentos_agrupados', through='producao.ContribuicaoOP', to='producao.ordemproducao'),
        ),
    ]
