# Generated by Django 4.2.21 on 2025-07-25 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_alter_maquina_options_remove_maquina_ano_and_more'),
        ('producao', '0034_apontamentolancamentoagrupado_contribuicaoop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgrupamentoLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Agrupamento para Lançamento',
                'verbose_name_plural': 'Agrupamentos para Lançamento',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AlterModelOptions(
            name='contribuicaoop',
            options={'verbose_name': 'Contribuição de OP no Lançamento', 'verbose_name_plural': 'Contribuições de OPs nos Lançamentos'},
        ),
        migrations.RemoveField(
            model_name='paradalancamentoagrupado',
            name='lancamento_agrupado',
        ),
        migrations.AlterField(
            model_name='contribuicaoop',
            name='ordem_producao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contribuicoes_op', to='producao.ordemproducao'),
        ),
        migrations.AlterField(
            model_name='contribuicaoop',
            name='quantidade_placas_contribuida',
            field=models.DecimalField(decimal_places=4, help_text='Quantidade de placas que esta OP específica contribuiu neste lançamento.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='status',
            field=models.CharField(choices=[('PENDENTE_CONFERENCIA', 'Pendente de Conferência PCP'), ('PENDENTE', 'Pendente'), ('EM_PRODUCAO', 'Em Produção'), ('AGUARDANDO_CORTE', 'Aguardando Corte'), ('PAUSADO', 'Pausado'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado'), ('REPROGRAMADO', 'Reprogramado')], default='PENDENTE_CONFERENCIA', max_length=50),
        ),
        migrations.CreateModel(
            name='LancamentoCilindro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_placas_total', models.DecimalField(decimal_places=4, help_text='Soma total de placas produzidas NESTE lançamento.', max_digits=10)),
                ('quantidade_grosas_total', models.DecimalField(decimal_places=4, default=0, help_text='Soma total de grosas produzidas NESTE lançamento. Calculado automaticamente.', max_digits=10)),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('agrupamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='producao.agrupamentolancamento')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.maquina', verbose_name='Cilindro')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.operador')),
            ],
            options={
                'verbose_name': 'Lançamento no Cilindro',
                'verbose_name_plural': 'Lançamentos no Cilindro',
                'ordering': ['-data_hora_inicio'],
            },
        ),
        migrations.AddField(
            model_name='agrupamentolancamento',
            name='ordens_producao',
            field=models.ManyToManyField(related_name='agrupamentos', to='producao.ordemproducao'),
        ),
        migrations.AddField(
            model_name='paradalancamentoagrupado',
            name='lancamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='producao.lancamentocilindro'),
        ),
        migrations.AlterField(
            model_name='contribuicaoop',
            name='lancamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribuicoes_op', to='producao.lancamentocilindro'),
        ),
        migrations.DeleteModel(
            name='ApontamentoLancamentoAgrupado',
        ),
    ]
